<?php

$title = 'All Messages';

$this->headTitle($title);

 ?>

 <h1><?=$this->escapeHtml($title)?></h1>  
 <!-- <input type="button"class="btn btn-warning" href="<?php echo $this->url('user',['action' => 'addmsg','content' => 'aaaa']) ?>">Add</input> -->

  <div class="row">
    <
    <input type="text" name="message" id="message" />
    <input type="button" class="btn btn-warning" id="sendMsg" value="Add"/>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>CreatedAt</th>
        <th>Content</th>
      </tr>
    </thead>
    <tbody id="tableList">
      
    </tbody>
  </table>
